### ISSUE TITLE
大佬下载好的chromedriver放在哪里

### ISSUE THREAD

**Issue by againboy** [lisztomania-Zero/learning-power#11]

**Comment by lisztomania-Zero** [comment]
可以自动下载啊！也可以在main.py目录下创建一个driver目录，然后放进去解压就可以了

**Comment by againboy** [comment]
DevTools listening on ws://127.0.0.1:50443/devtools/browser/a9effd42-411d-46eb-9c45-01817b1f956d
[4372:11904:1224/135720.259:ERROR:device_event_log_impl.cc(211)] [13:57:20.258] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
Traceback (most recent call last):
  File "C:\Users\WJw\Desktop\learning-power-0.31\main.py", line 19, in <module>
    task_manage = Task_Manage(driver=driver)
  File "C:\Users\WJw\Desktop\learning-power-0.31\task\task_manage.py", line 48, in __init__
    self.__refresh_user_msg()
  File "C:\Users\WJw\Desktop\learning-power-0.31\task\task_manage.py", line 59, in __refresh_user_msg
    self.__user_msg[USER_KEYS[4]] = analysis_msg.task_bar
  File "C:\Users\WJw\Desktop\learning-power-0.31\tools\analysis.py", line 112, in task_bar
    task_bar[TASK_ID[task['ruleId']]] = task
KeyError: 21

**Comment by againboy** [comment]
看大不懂。。

**Comment by lisztomania-Zero** [comment]
你重新下载一下
