### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by ggggggggggithub** [lisztomania-Zero/learning-power#22]
Traceback (most recent call last):
  File "mmm.py", line 12, in <module>
    from inside.Driver.Driver_Manage import DRIVER_MANAGE
  File "C:\bb\AutoXue3\learning-power-master\inside\Driver\Driver_Manage.py", line 13, in <module>
    from inside.Config.Api import API
  File "C:\bb\AutoXue3\learning-power-master\inside\Config\Api.py", line 9, in <module>
    from ping3 import ping
ModuleNotFoundError: No module named 'ping3'

**Comment by lisztomania-Zero** [comment]
> Traceback (most recent call last):
> File "mmm.py", line 12, in
> from inside.Driver.Driver_Manage import DRIVER_MANAGE
> File "C:\bb\AutoXue3\learning-power-master\inside\Driver\Driver_Manage.py", line 13, in
> from inside.Config.Api import API
> File "C:\bb\AutoXue3\learning-power-master\inside\Config\Api.py", line 9, in
> from ping3 import ping
> ModuleNotFoundError: No module named 'ping3'

ping3依赖已移除，你重新下载
