### ISSUE TITLE
每周和专项答题都会出错。。

### ISSUE THREAD

**Issue by matthkewk** [lisztomania-Zero/learning-power#23]
![QQ截图20210131002603](https://user-images.githubusercontent.com/67943258/106361948-17f46b00-635b-11eb-9004-70f972a2512e.png)

**Comment by lisztomania-Zero** [comment]
内存错误，你内存多大？？

**Comment by 506430136** [comment]
可选任务:
1、文章	2、视频	3、每日答题	4、每周答题	5、专项答题	
选择任务(空为退出):5
抓取答案完成
答题:  40%|███████████▏                | 4/10 [00:00<00:01,  4.57题/s]Traceback (most recent call last):
  File "E:\PythonWork\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "E:\PythonWork\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
    self.__Check_Project_Answer()
  File "E:\PythonWork\learning-power-master\inside\Task\Task_Manage.py", line 192, in __Check_Project_Answer
    temp.Do(link=API().Project_Answer_Topic.geturl().format(num=iid))
  File "E:\PythonWork\learning-power-master\inside\Task\Task_Answer.py", line 178, in Do
    self.__Do()
  File "E:\PythonWork\learning-power-master\inside\Task\Task_Answer.py", line 156, in __Do
    topic_submit.click()
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by matthkewk** [comment]
> 内存错误，你内存多大？？

16g..应该不是内存问题吧。。前面我试了都正常且成功 就是4 5会有问题

**Comment by lisztomania-Zero** [comment]
> > 内存错误，你内存多大？？
> 
> 16g..应该不是内存问题吧。。前面我试了都正常且成功 就是4 5会有问题

程序运行时，最高也就占了400M内存，其中驱动占了一大半；
最后一个单词（内存错误），报错的位置是get_nowait()
这个错误我以为是Python的Queue队列问题，我查了资料、做了实验，往队列里面填充一百万的数据内存占了大概二三百的样子，但是清空队列后就恢复正常了，而程序每做一个任务就会清空一次队列，所以不应当出现内存错误，我这边没出现过内存错误，我的内存只有8G。我在Network.py中增加了内存检测，当占有率到达百分之九十五时，就会执行垃圾回收，不过用处应该不大。

**Comment by lisztomania-Zero** [comment]
我现在也搞不清为什么会出这样的错误，如果你找到原因，希望你能告诉我

**Comment by matthkewk** [comment]
更新后又试了一次已经没问题了，45都可以完美注入完成 感谢大佬！

> 我现在也搞不清为什么会出这样的错误，如果你找到原因，希望你能告诉我
