### ISSUE TITLE
最新版不知道什么原因出错.

### ISSUE THREAD

**Issue by nqianaaron** [lisztomania-Zero/learning-power#25]
目前的是正式版谷歌浏览器.但是版本号不是94.是Google Chrome 已是最新版本
版本 88.0.4324.104（正式版本） （64 位）
但是这个driver自动更新的.应该也不至于啊?
出错详情如下:
是否静音(Y/n):y
是否显示自动化过程(y/N):n
是否持久化登录(Y/n):y
检测到驱动未下载
驱动自动下载中
chromedriver_win32.zip: 100%|████| 4.59M/4.59M [00:00<00:00, 5.55MB/s]
驱动自动下载完毕
文件大小为4.378110885620117MB
Traceback (most recent call last):
  File "C:\Users\hellsion\Desktop\learning-power-master\main.py", line 27, in <module>
    network.Init(driver=driver.Task)
  File "C:\Users\hellsion\Desktop\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
    return DRIVER_INIT().Task_Driver
  File "C:\Users\hellsion\Desktop\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
    self.__instances['Task'] = Chrome(
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\hellsion\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17763 x86_64)

**Comment by lisztomania-Zero** [comment]
![image](https://user-images.githubusercontent.com/50130180/106374744-c5e63080-63c0-11eb-837c-4d01a300a8ae.png)
![image](https://user-images.githubusercontent.com/50130180/106374757-dbf3f100-63c0-11eb-80d5-168d3d743cd0.png)
我的没问题啊？你是什么操作系统？

**Comment by 506430136** [comment]
这个你自己去阿里镜像下载对应版本的驱动，解压后放到根目录的Driver目录下，就可以了

**Comment by lisztomania-Zero** [comment]
> 这个你自己去阿里镜像下载对应版本的驱动，解压后放到根目录的Driver目录下，就可以了
