### ISSUE TITLE
二维码不显示

### ISSUE THREAD

**Issue by 506430136** [lisztomania-Zero/learning-power#26]
运行后如果 选择“是否显示自动化过程(y/N):y”，打开浏览器后，不显示图片，也不切换二维码页面，如果复制链接，重新打开浏览器，手动点击一切正常，也可以显示二维码。
E:\PythonWork\learning-power-master\venv\Scripts\python.exe E:/PythonWork/learning-power-master/main.py
是否静音(Y/n):y
是否显示自动化过程(y/N):n
是否持久化登录(Y/n):y
Traceback (most recent call last):
File "E:\PythonWork\learning-power-master\main.py", line 28, in
if LOGIN(task_driver=driver.Task).Login():
File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 324, in Login
return self._Login()
File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 277, in _Login
qr = self.__Get_QR()
File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 82, in __Get_QR
qr_iframe = self.__QR_Iframe()
File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 59, in __QR_Iframe
return self.__wait.until(iframe_Ec)
File "E:\PythonWork\learning-power-master\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by 506430136** [comment]
是不是登录按钮那个链接是图片格式，<a class="icon login-icon"></a> 
所以禁止图片后就无法模拟点击，造成等待超时？

**Comment by lisztomania-Zero** [comment]
> 运行后如果 选择“是否显示自动化过程(y/N):y”，打开浏览器后，不显示图片，也不切换二维码页面，如果复制链接，重新打开浏览器，手动点击一切正常，也可以显示二维码。
> E:\PythonWork\learning-power-master\venv\Scripts\python.exe E:/PythonWork/learning-power-master/main.py
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):n
> 是否持久化登录(Y/n):y
> Traceback (most recent call last):
> File "E:\PythonWork\learning-power-master\main.py", line 28, in
> if LOGIN(task_driver=driver.Task).Login():
> File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 324, in Login
> return self._Login()
> File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 277, in _Login
> qr = self.__Get_QR()
> File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 82, in __Get_QR
> qr_iframe = self.__QR_Iframe()
> File "E:\PythonWork\learning-power-master\inside\Login\Login.py", line 59, in __QR_Iframe
> return self.__wait.until(iframe_Ec)
> File "E:\PythonWork\learning-power-master\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
> raise TimeoutException(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message:

![image](https://user-images.githubusercontent.com/50130180/106376719-d8696580-63d2-11eb-99fb-76ceb9ff28c9.png)
不显示图片是因为这个文件inside/Driver/Driver_Init.py初始化驱动的时候选择了无图模式，以便于更快的加载页面

**Comment by lisztomania-Zero** [comment]
> 是不是登录按钮那个链接是图片格式，
> 所以禁止图片后就无法模拟点击，造成等待超时？

不是不是，你这个二维码的iframe10秒内没加载出来，报的超时错误

**Comment by 506430136** [comment]
在那里设置的时长？我修改下，增加点时间

**Comment by lisztomania-Zero** [comment]
> > 是不是登录按钮那个链接是图片格式，
> > 所以禁止图片后就无法模拟点击，造成等待超时？
> 
> 不是不是，你这个二维码的iframe10秒内没加载出来，报的超时错误


> 在那里设置的时长？我修改下，增加点时间

你网速咋样？

**Comment by 506430136** [comment]
我单独打开没问题啊，基本2秒就能打开页面

**Comment by lisztomania-Zero** [comment]
> > > 是不是登录按钮那个链接是图片格式，
> > > 所以禁止图片后就无法模拟点击，造成等待超时？
> > 
> > 
> > 不是不是，你这个二维码的iframe10秒内没加载出来，报的超时错误
> 
> > 在那里设置的时长？我修改下，增加点时间
> 
> 你网速咋样？

![image](https://user-images.githubusercontent.com/50130180/106376802-6e9d8b80-63d3-11eb-96c4-d391549b893e.png)
这个文件inside/Login/Login.py

**Comment by lisztomania-Zero** [comment]
> 我单独打开没问题啊，基本2秒就能打开页面

？？？那咋加载不出来。如果修改时间没用的话你直接把无图模式改成1，或者直接删掉那一行

**Comment by 506430136** [comment]
> > 我单独打开没问题啊，基本2秒就能打开页面
> 
> ？？？那咋加载不出来。如果修改时间没用的话你直接把无图模式改成1，或者直接删掉那一行

OK，我试试

**Comment by 506430136** [comment]
无图模式改成1后，第一次自己加载没出来，手动刷新后加载出来了

**Comment by 506430136** [comment]
可选任务:
1、文章	2、视频	3、每日答题	4、每周答题	5、专项答题	
选择任务(空为退出):1

这里需要手动选择每一项然后执行吗？
能不能自动逐项去完成？

**Comment by lisztomania-Zero** [comment]
> 无图模式改成1后，第一次自己加载没出来，手动刷新后加载出来了



> 可选任务:
> 1、文章 2、视频 3、每日答题 4、每周答题 5、专项答题
> 选择任务(空为退出):1
> 
> 这里需要手动选择每一项然后执行吗？
> 能不能自动逐项去完成？

你想要全选，对吧

**Comment by lisztomania-Zero** [comment]
> > 无图模式改成1后，第一次自己加载没出来，手动刷新后加载出来了
> 
> > 可选任务:
> > 1、文章 2、视频 3、每日答题 4、每周答题 5、专项答题
> > 选择任务(空为退出):1
> > 这里需要手动选择每一项然后执行吗？
> > 能不能自动逐项去完成？
> 
> 你想要全选，对吧

你等一下，我改一下

**Comment by 506430136** [comment]
全选后，系统根据完成得分情况，自动去判断，执行后续未完成的项目

**Comment by 506430136** [comment]
提个建议，答题部分速度太快了，应该尽量模拟人点击的速度，一道题一般最短也有3秒的样子，太快了可能会被系统发现。

**Comment by lisztomania-Zero** [comment]
增加全选了，发现专项答题问题，并修复了；
你看着快，其实时间是20-50秒的随机时间，因为修改了数据包

**Comment by 506430136** [comment]
> 增加全选了，发现专项答题问题，并修复了；
> 你看着快，其实时间是20-50秒的随机时间，因为修改了数据包

哦，是的，我看着都是秒答题，专项答题的bug修好了啊，我刚自己答2完了，明天再试试

**Comment by lisztomania-Zero** [comment]
> > 增加全选了，发现专项答题问题，并修复了；
> > 你看着快，其实时间是20-50秒的随机时间，因为修改了数据包
> 
> 哦，是的，我看着都是秒答题，专项答题的bug修好了啊，我刚自己答2完了，明天再试试

好的，有什么意见或想法可以提出来，一起研究一下

**Comment by 506430136** [comment]
嗯，我也好好学习下你的源码
