### ISSUE TITLE
专项答题显示错误

### ISSUE THREAD

**Issue by scott244** [lisztomania-Zero/learning-power#27]
答题:  50%|██████████████              | 5/10 [00:01<00:01,  4.31题/s]Traceback (most recent call last):
  File "C:\Users\MLong\Downloads\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
    self.__Check_Project_Answer()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 192, in __Check_Project_Answer
    temp.Do(link=API().Project_Answer_Topic.geturl().format(num=iid))
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Answer.py", line 178, in Do
    self.__Do()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Answer.py", line 156, in __Do
    topic_submit.click()
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by lisztomania-Zero** [comment]
最后的网页界面能截个图吗，或者告诉我这是专项答题哪个题目？这是没获取到提交按钮，导致的错误。

**Comment by scott244** [comment]
就是1月30号发布的专项题目

**Comment by lisztomania-Zero** [comment]
> 就是1月30号发布的专项题目

修复了

**Comment by scott244** [comment]
Traceback (most recent call last):
  File "C:\Users\MLong\Downloads\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
    self.__Check_Project_Answer()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 187, in __Check_Project_Answer
    iid = TASK_INIT().Assigning_Project_Answer(token=token)
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Init.py", line 156, in Assigning_Project_Answer
    data = json.loads(base64.b64decode(data['data_str']).decode('utf-8'))
KeyError: 'data_str'

**Comment by lisztomania-Zero** [comment]
> 还是不行，我重新下载了你的inside文件，但是依旧显示“AttributeError: 'NoneType' object has no attribute 'click'“

我想想，办法吧

**Comment by scott244** [comment]
现在每周和专项答题都显示Traceback (most recent call last):
  File "C:\Users\MLong\Downloads\learning-power-master\main.py", line 33, in <module>
    task.Task()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 214, in Task
    self.__Check_Project_Answer()
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Manage.py", line 187, in __Check_Project_Answer
    iid = TASK_INIT().Assigning_Project_Answer(token=token)
  File "C:\Users\MLong\Downloads\learning-power-master\inside\Task\Task_Init.py", line 156, in Assigning_Project_Answer
    data = json.loads(base64.b64decode(data['data_str']).decode('utf-8'))
KeyError: 'data_str'

**Comment by scott244** [comment]
而每日答题达到80%就停止不动了！

**Comment by againboy** [comment]
> 还是不行，我重新下载了你的inside文件，但是依旧显示“AttributeError: 'NoneType' object has no attribute 'click'“

我现在也是这个问题
