### ISSUE TITLE
专项答题从未成功

### ISSUE THREAD

**Issue by justplus** [lisztomania-Zero/learning-power#29]
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
专项答题得分:0/10.0
抓取答案完成
检测到提交，注入中
检测到本次提交为干扰
检测到提交，注入中
注入成功
Traceback (most recent call last):
  File "tools/learning-power/inside/Task/Task_Answer.py", line 178, in Do
    self.__Do()
  File "tools/learning-power/inside/Task/Task_Answer.py", line 156, in __Do
    topic_submit.click()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="button" class="ant-btn submit-btn ant-btn-primary ant-btn-background-ghost">...</button> is not clickable at point (574, 580). Other element would receive the click: <div tabindex="-1" class="ant-modal-wrap ant-modal-centered ant-modal-confirm-centered" role="dialog">...</div>
  (Session info: headless chrome=88.0.4324.96)
  (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Mac OS X 11.1.0 x86_64)

**Comment by lisztomania-Zero** [comment]
哈？

**Comment by lisztomania-Zero** [comment]
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 专项答题得分:0/10.0
> 抓取答案完成
> 检测到提交，注入中
> 检测到本次提交为干扰
> 检测到提交，注入中
> 注入成功
> Traceback (most recent call last):
> File "tools/learning-power/inside/Task/Task_Answer.py", line 178, in Do
> self.__Do()
> File "tools/learning-power/inside/Task/Task_Answer.py", line 156, in __Do
> topic_submit.click()
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
> self._execute(Command.CLICK_ELEMENT)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
> return self._parent.execute(command, params)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element ... is not clickable at point (574, 580). Other element would receive the click:
> 
> ...
> 
> (Session info: headless chrome=88.0.4324.96)
> (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Mac OS X 11.1.0 x86_64)

都是，提交按钮没加载出来

**Comment by lisztomania-Zero** [comment]
我想想办法，你可以多试几次

**Comment by justplus** [comment]
这个问题怎讲？注入的时候报参数错误~

**Comment by lisztomania-Zero** [comment]
> 这个问题怎讲？注入的时候报参数错误~

这是提交或下一题按钮出问题了，你能提供一下是哪个专项答题吗？

**Comment by justplus** [comment]
每一题

**Comment by lisztomania-Zero** [comment]
> 每一题

我没有Mac，只有Mac10的虚拟机
你的是Mac11，我在Mac10上运行是没问题的
你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
或者你重新下载试试，我今天早上更新了。

**Comment by justplus** [comment]
> > 每一题
> 
> 我没有Mac，只有Mac10的虚拟机
> 你的是Mac11，我在Mac10上运行是没问题的
> 你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
> 或者你重新下载试试，我今天早上更新了。

页面是有提交按钮的，显示的是 “网络开小差”，dev tools查看是submitv3接口报500错误：提示接口参数不合法

**Comment by lisztomania-Zero** [comment]
> > > 每一题
> > 
> > 
> > 我没有Mac，只有Mac10的虚拟机
> > 你的是Mac11，我在Mac10上运行是没问题的
> > 你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
> > 或者你重新下载试试，我今天早上更新了。
> 
> 页面是有提交按钮的，显示的是 “网络开小差”，dev tools查看是submitv3接口报500错误：提示接口参数不合法

我知道了，是因为专项答题的答案是过滤提示信息中的红字部分，而你现在答的那组专项答题中存在视频题目，所以答案提取失败，然后就提交服务器的时候通不过
不过我做了修复，你使用最新版本应该没问题

**Comment by Zero09** [comment]
> > > > 每一题
> > > 
> > > 
> > > 我没有Mac，只有Mac10的虚拟机
> > > 你的是Mac11，我在Mac10上运行是没问题的
> > > 你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
> > > 或者你重新下载试试，我今天早上更新了。
> > 
> > 
> > 页面是有提交按钮的，显示的是 “网络开小差”，dev tools查看是submitv3接口报500错误：提示接口参数不合法
> 
> 我知道了，是因为专项答题的答案是过滤提示信息中的红字部分，而你现在答的那组专项答题中存在视频题目，所以答案提取失败，然后就提交服务器的时候通不过
> 不过我做了修复，你使用最新版本应该没问题

大佬 貌似还是有问题。我直接clone代码下来运行的，我看了自动化过程，没有出行视频的。最后交卷也是网络开小差。能再帮忙看看吗

**Comment by e790a8** [comment]
> > > > > 每一题
> > > > 
> > > > 
> > > > 我没有Mac，只有Mac10的虚拟机
> > > > 你的是Mac11，我在Mac10上运行是没问题的
> > > > 你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
> > > > 或者你重新下载试试，我今天早上更新了。
> > > 
> > > 
> > > 页面是有提交按钮的，显示的是 “网络开小差”，dev tools查看是submitv3接口报500错误：提示接口参数不合法
> > 
> > 
> > 我知道了，是因为专项答题的答案是过滤提示信息中的红字部分，而你现在答的那组专项答题中存在视频题目，所以答案提取失败，然后就提交服务器的时候通不过
> > 不过我做了修复，你使用最新版本应该没问题
> 
> 大佬 貌似还是有问题。我直接clone代码下来运行的，我看了自动化过程，没有出行视频的。最后交卷也是网络开小差。能再帮忙看看吗

哪一题？

**Comment by Zero09** [comment]
> > > > > > 每一题
> > > > > 
> > > > > 
> > > > > 我没有Mac，只有Mac10的虚拟机
> > > > > 你的是Mac11，我在Mac10上运行是没问题的
> > > > > 你可以选择显示自动化过程，然后报错之后，把浏览器界面截图我看看吗？
> > > > > 或者你重新下载试试，我今天早上更新了。
> > > > 
> > > > 
> > > > 页面是有提交按钮的，显示的是 “网络开小差”，dev tools查看是submitv3接口报500错误：提示接口参数不合法
> > > 
> > > 
> > > 我知道了，是因为专项答题的答案是过滤提示信息中的红字部分，而你现在答的那组专项答题中存在视频题目，所以答案提取失败，然后就提交服务器的时候通不过
> > > 不过我做了修复，你使用最新版本应该没问题
> > 
> > 
> > 大佬 貌似还是有问题。我直接clone代码下来运行的，我看了自动化过程，没有出行视频的。最后交卷也是网络开小差。能再帮忙看看吗
> 
> 哪一题？

失败会重新做题，我看每次都没成功，但是答案应该都是捕捉到正确的了。就是提交那一下还有点问题。网络开小差。自己用网页做题就正常提交。

**Comment by chendy218** [comment]
不忘初心、牢记使命”主题教育专项答题
所有的填空题都填1
所有的选择题都全选，最后提交显示网络开小差。
