### ISSUE TITLE
重新下载新版后出现错误  [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by woodenhao** [lisztomania-Zero/learning-power#30]
之前用的还行 自己答题 用程序走一下123任务就OK了 突然看见更新了 下载了新版就一直出问题

是否静音(Y/n):y
是否显示自动化过程(y/N):n
是否持久化登录(Y/n):y
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "C:\Users\woode\Desktop\pythonlol\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen(
  File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by lisztomania-Zero** [comment]
> 之前用的还行 自己答题 用程序走一下123任务就OK了 突然看见更新了 下载了新版就一直出问题
> 
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):n
> 是否持久化登录(Y/n):y
> Traceback (most recent call last):
> File "main.py", line 24, in
> MITMDUMP().Open()
> File "C:\Users\woode\Desktop\pythonlol\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
> self.__mitmdump = subprocess.Popen(
> File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
> hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。

这是拦截注入脚本文件没找到，你的inside\Task\Mitmdump目录下有Intercept.py这个文件没？

**Comment by woodenhao** [comment]
> > 之前用的还行 自己答题 用程序走一下123任务就OK了 突然看见更新了 下载了新版就一直出问题
> > 是否静音(Y/n):y
> > 是否显示自动化过程(y/N):n
> > 是否持久化登录(Y/n):y
> > Traceback (most recent call last):
> > File "main.py", line 24, in
> > MITMDUMP().Open()
> > File "C:\Users\woode\Desktop\pythonlol\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
> > self.__mitmdump = subprocess.Popen(
> > File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in **init**
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
> > hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> 
> 这是拦截注入脚本文件没找到，你的inside\Task\Mitmdump目录下有Intercept.py这个文件没？

有的

**Comment by lisztomania-Zero** [comment]
> > > 之前用的还行 自己答题 用程序走一下123任务就OK了 突然看见更新了 下载了新版就一直出问题
> > > 是否静音(Y/n):y
> > > 是否显示自动化过程(y/N):n
> > > 是否持久化登录(Y/n):y
> > > Traceback (most recent call last):
> > > File "main.py", line 24, in
> > > MITMDUMP().Open()
> > > File "C:\Users\woode\Desktop\pythonlol\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
> > > self.__mitmdump = subprocess.Popen(
> > > File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in **init**
> > > self._execute_child(args, executable, preexec_fn, close_fds,
> > > File "C:\Users\woode\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
> > > hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> > > FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> > 
> > 
> > 这是拦截注入脚本文件没找到，你的inside\Task\Mitmdump目录下有Intercept.py这个文件没？
> 
> 有的

你重新下载试试，或者换个盘试试，如果还不行，就把你的系统版本发我一下

**Comment by legolas-zeng** [comment]
![image](https://user-images.githubusercontent.com/27952739/107171096-e59ed980-69fc-11eb-956b-6751159b38aa.png)
你好，我这没有Intercept.py文件是什么问题

**Comment by chendy218** [comment]
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):y
是否使用百度AI(y/N):y
Traceback (most recent call last):
  File "E:\mydata\learning-power-master\main.py", line 24, in <module>
    MITMDUMP().Open()
  File "E:\mydata\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 36, in Open
    self.__mitmdump = subprocess.Popen(
  File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\JY-13\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

C:\Users\JY-13>python E:\mydata\learning-power-master\inside\Task\Mitmdump\Mitmdump.py
Traceback (most recent call last):
  File "E:\mydata\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 11, in <module>
    from inside.Config.Path import PATH
ModuleNotFoundError: No module named 'inside'


PIP依赖库好了

**Comment by qingcheng123** [comment]
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    MITMDUMP().Open()
  File "P:\learning-power-master\inside\Task\Mitmdump\Mitmdump.py", line 37, in Open
    ['mitmdump', '-q', '-p', '8080', '-s', PATH().Script]
  File "D:\Anaconda soft\Ana install\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda soft\Ana install\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

大佬们，这是呢么回事啊，第一次弄
