### ISSUE TITLE
更新版本后运行出错

### ISSUE THREAD

**Issue by againboy** [lisztomania-Zero/learning-power#31]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from inside.Driver.Driver_Manage import DRIVER_MANAGE
  File "D:\Program Files\learning-power-1.0\inside\Driver\Driver_Manage.py", line 13, in <module>
    from inside.Config.Api import API
  File "D:\Program Files\learning-power-1.0\inside\Config\Api.py", line 9, in <module>
    from ping3 import ping
ModuleNotFoundError: No module named 'ping3'

**Comment by nqianaaron** [comment]
你这个好像是没有ping3的包,重新安装一下requirements试试?

**Comment by lisztomania-Zero** [comment]
> Traceback (most recent call last):
> File "main.py", line 12, in
> from inside.Driver.Driver_Manage import DRIVER_MANAGE
> File "D:\Program Files\learning-power-1.0\inside\Driver\Driver_Manage.py", line 13, in
> from inside.Config.Api import API
> File "D:\Program Files\learning-power-1.0\inside\Config\Api.py", line 9, in
> from ping3 import ping
> ModuleNotFoundError: No module named 'ping3'

最新版已经移除ping3了，你更新一下

**Comment by againboy** [comment]
> > Traceback (most recent call last):
> > File "main.py", line 12, in
> > from inside.Driver.Driver_Manage import DRIVER_MANAGE
> > File "D:\Program Files\learning-power-1.0\inside\Driver\Driver_Manage.py", line 13, in
> > from inside.Config.Api import API
> > File "D:\Program Files\learning-power-1.0\inside\Config\Api.py", line 9, in
> > from ping3 import ping
> > ModuleNotFoundError: No module named 'ping3'
> 
> 最新版已经移除ping3了，你更新一下

嗯 重新安装了 出现这个是啥问题？
D:\python\Scripts\mitmdump: No such script
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    if LOGIN(task_driver=driver.Task).Login():
  File "D:\Program Files\learning-power-1.0\inside\Login\Login.py", line 324, in Login
    return self._Login()
  File "D:\Program Files\learning-power-1.0\inside\Login\Login.py", line 275, in _Login
    self.__driver.get(url=API().Login.geturl())
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: headless chrome=88.0.4324.96)
  (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Windows NT 10.0.18363 x86_64)

**Comment by lisztomania-Zero** [comment]
> in



> > > Traceback (most recent call last):
> > > File "main.py", line 12, in
> > > from inside.Driver.Driver_Manage import DRIVER_MANAGE
> > > File "D:\Program Files\learning-power-1.0\inside\Driver\Driver_Manage.py", line 13, in
> > > from inside.Config.Api import API
> > > File "D:\Program Files\learning-power-1.0\inside\Config\Api.py", line 9, in
> > > from ping3 import ping
> > > ModuleNotFoundError: No module named 'ping3'
> > 
> > 
> > 最新版已经移除ping3了，你更新一下
> 
> 嗯 重新安装了 出现这个是啥问题？
> D:\python\Scripts\mitmdump: No such script
> Traceback (most recent call last):
> File "main.py", line 28, in
> if LOGIN(task_driver=driver.Task).Login():
> File "D:\Program Files\learning-power-1.0\inside\Login\Login.py", line 324, in Login
> return self._Login()
> File "D:\Program Files\learning-power-1.0\inside\Login\Login.py", line 275, in _Login
> self.__driver.get(url=API().Login.geturl())
> File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
> self.execute(Command.GET, {'url': url})
> File "D:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "D:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
> (Session info: headless chrome=88.0.4324.96)
> (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Windows NT 10.0.18363 x86_64)

根据你的报错信息：
1、拦截脚本未加载
2、浏览器代理连接错误
建议：
查看inside\Task\Mitmdump目录下有Intercept.py这个文件没？
检查一下计算机的代理设置，有没有什么程序占用了8080；

**Comment by againboy** [comment]
> 根据你的报错信息：
> 1、拦截脚本未加载
> 2、浏览器代理连接错误
> 建议：
> 查看inside\Task\Mitmdump目录下有Intercept.py这个文件没？
> 检查一下计算机的代理设置，有没有什么程序占用了8080；

这个问题解决了，我把文件夹放在D盘根目录下就没问题了，不过开始运行程序又出现这个情况
可选任务:
1、文章 2、视频 3、每日答题     4、每周答题     5、专项答题
选择任务(空为退出):2
正在分发视频任务
检测到视频任务数不足，自动获取任务集
解析任务集中
解析为文章任务集
解析为文章任务集
解析为文章任务集
解析为文章任务集
解析为文章任务集
解析为文章任务集
解析为文章任务集
解析为文章任务集

**Comment by lisztomania-Zero** [comment]
正常，因为一开始数据库中并没有文章和视频任务

**Comment by againboy** [comment]
> 正常，因为一开始数据库中并没有文章和视频任务
谢谢，明白了，我等的时间要稍微长一点

**Comment by againboy** [comment]
> 正常，因为一开始数据库中并没有文章和视频任务

问一下，多个任务是用什么符号连起来？

**Comment by lisztomania-Zero** [comment]
？

> > 正常，因为一开始数据库中并没有文章和视频任务
> 
> 问一下，多个任务是用什么符号连起来？

？

**Comment by lisztomania-Zero** [comment]
> > 正常，因为一开始数据库中并没有文章和视频任务
> 
> 问一下，多个任务是用什么符号连起来？
啥意思？

**Comment by againboy** [comment]
> > > 正常，因为一开始数据库中并没有文章和视频任务
> > 
> > 
> > 问一下，多个任务是用什么符号连起来？
> > 啥意思？

可选任务:
1、文章 2、视频 3、每日答题     4、每周答题     5、专项答题
选择任务(空为退出):

任务全选怎么填？

**Comment by lisztomania-Zero** [comment]
不是有个全选选项吗？就是输入0

**Comment by lisztomania-Zero** [comment]
> > > > 正常，因为一开始数据库中并没有文章和视频任务
> > > 
> > > 
> > > 问一下，多个任务是用什么符号连起来？
> > > 啥意思？
> 
> 可选任务:
> 1、文章 2、视频 3、每日答题 4、每周答题 5、专项答题
> 选择任务(空为退出):
> 
> 任务全选怎么填？

![image](https://user-images.githubusercontent.com/50130180/106699853-a3e9e980-661e-11eb-9389-d7c4e8a6400e.png)

**Comment by againboy** [comment]
![image](https://user-images.githubusercontent.com/38928909/106700560-10191d00-6620-11eb-9e2c-b3b2680de979.png)
这个全选我这里没有哎

**Comment by againboy** [comment]
![image](https://user-images.githubusercontent.com/38928909/106700632-32ab3600-6620-11eb-8607-de208201e196.png)
我直接打0，他不睬我哈

**Comment by againboy** [comment]
![image](https://user-images.githubusercontent.com/38928909/106700729-5c645d00-6620-11eb-8928-755326bc7bcf.png)
打了一个3，这是出错吗？

**Comment by lisztomania-Zero** [comment]
> ![image](https://user-images.githubusercontent.com/38928909/106700729-5c645d00-6620-11eb-8928-755326bc7bcf.png)
> 打了一个3，这是出错吗？

你这不是最新版
