### ISSUE TITLE
大佬我这个是啥意思、、 运行不成功

### ISSUE THREAD

**Issue by nie-e** [lisztomania-Zero/learning-power#33]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    os.system(command=SYSTEM().Clear)
TypeError: system() got an unexpected keyword argument 'command'

**Comment by lisztomania-Zero** [comment]
> Traceback (most recent call last):
> File "main.py", line 22, in
> os.system(command=SYSTEM().Clear)
> TypeError: system() got an unexpected keyword argument 'command'

你是Py3？

**Comment by nie-e** [comment]
> > 追溯（最近一次呼叫最近）：
> > os.system中的文件“ main.py”，第22行，
> > system。（command = SYSTEM（）。Clear）
> > TypeError：system（）得到了意外的关键字参数“ command”
> 
> 你是Py3？

是的是的，我用的py3   mac本。。。

**Comment by nie-e** [comment]
➜  learning-power git:(master) ✗ python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from inside.Config.System import SYSTEM
  File "/Users/xuan/Demo/youyisi/xuexi/learning-power/inside/Config/System.py", line 30
    def Supports(self) -> FrozenSet:
                       ^
SyntaxError: invalid syntax


直接运行的话，就是这个样子。。

**Comment by nie-e** [comment]
哎，我放弃了， mac毛病太多，我开虚拟机win了。。难受

**Comment by lisztomania-Zero** [comment]
Mac版本多少？
不应该呀，我这没问题啊
![image](https://user-images.githubusercontent.com/50130180/106851534-673af280-66f1-11eb-8f29-507d6f55a2da.png)

**Comment by nie-e** [comment]
我用的新版本的11.1了

**Comment by nie-e** [comment]
是否静音(Y/n):y
是否显示自动化过程(y/N):n
是否持久化登录(Y/n):y
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    network.Init(driver=driver.Task)
  File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
    return DRIVER_INIT().Task_Driver
  File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
    self.__instances['Task'] = Chrome(
  File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.18363 x86_64)


C:\Users\xuan\Desktop\learning-power-master>


大佬我傻了。。。。
win也不行。。。天啊

**Comment by lisztomania-Zero** [comment]
> 是否静音(Y/n):y
> 是否显示自动化过程(y/N):n
> 是否持久化登录(Y/n):y
> Traceback (most recent call last):
> File "main.py", line 27, in
> network.Init(driver=driver.Task)
> File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
> return DRIVER_INIT().Task_Driver
> File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
> self.__instances['Task'] = Chrome(
> File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in **init**
> RemoteWebDriver.**init**(
> File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.18363 x86_64)
> 
> C:\Users\xuan\Desktop\learning-power-master>
> 
> 大佬我傻了。。。。
> win也不行。。。天啊

![image](https://user-images.githubusercontent.com/50130180/106857939-dd445700-66fb-11eb-83c3-2fc0a207494c.png)
你注册表中的版本和你Chrome版本对不上

**Comment by lisztomania-Zero** [comment]
> > 是否静音(Y/n):y
> > 是否显示自动化过程(y/N):n
> > 是否持久化登录(Y/n):y
> > Traceback (most recent call last):
> > File "main.py", line 27, in
> > network.Init(driver=driver.Task)
> > File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
> > return DRIVER_INIT().Task_Driver
> > File "C:\Users\xuan\Desktop\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
> > self.__instances['Task'] = Chrome(
> > File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in **init**
> > RemoteWebDriver.**init**(
> > File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "C:\Users\xuan\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> > (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.18363 x86_64)
> > C:\Users\xuan\Desktop\learning-power-master>
> > 大佬我傻了。。。。
> > win也不行。。。天啊
> 
> ![image](https://user-images.githubusercontent.com/50130180/106857939-dd445700-66fb-11eb-83c3-2fc0a207494c.png)
> 你注册表中的版本和你Chrome版本对不上

导致驱动下载的版本不对

**Comment by jxphzxm** [comment]
> ➜  learning-power git:(master) ✗ python main.py
> 
> Traceback (most recent call last):
> 
>   File "main.py", line 11, in <module>
> 
>     from inside.Config.System import SYSTEM
> 
>   File "/Users/xuan/Demo/youyisi/xuexi/learning-power/inside/Config/System.py", line 30
> 
>     def Supports(self) -> FrozenSet:
> 
>                        ^
> 
> SyntaxError: invalid syntax
> 
> 
> 
> 
> 
> 直接运行的话，就是这个样子。。

跟我遇到的情况一模一样，我一开始安装就报错，折腾了一个晚上
安装要执行pip3 install -r requirements.txt
运行先执行sudo su获取权限，再执行python3 main.py
我也不知道为什么，反正就可以了

**Comment by nie-e** [comment]
> > ➜学习能力git：（master）✗python main.py
> > 追溯（最近一次通话）：
> > 在第11行的文件“ main.py”中 
> > ```
> > from inside.Config.System import SYSTEM
> > ```
> > 
> > 
> > 文件“ /Users/xuan/Demo/youyisi/xuexi/learning-power/inside/Config/System.py”，第30行
> > ```
> > def Supports(self) -> FrozenSet:
> > 
> >                    ^
> > ```
> > 
> > 
> > SyntaxError：语法无效
> > 直接运行的话，就是这个样子。。
> 
> 跟我遇到的情况一模一样，我一开始安装就报错，折腾了一个晚上
> 安装要执行pip3 install -r requirements.txt
> 运行先执行sudo su获取权限，再执行python3 main.py
> 我也不知道为什么，反正就可以了



root@siyangyuan-Pro learning-power # python3 main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from inside.Driver.Driver_Manage import DRIVER_MANAGE
  File "/Users/xuan/Demo/youyisi/xuexi/learning-power/inside/Driver/Driver_Manage.py", line 11, in <module>
    from selenium.webdriver.chrome.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium' 
这个是获取权限的报错，

➜  learning-power git:(master) ✗ sudo python3 main.py
Password:
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    os.system(command=SYSTEM().Clear)
TypeError: system() got an unexpected keyword argument 'command'

这个是正常没获取权限的报错。。= =， 这个安装依赖的时候，会有一群红色的报错，
