### ISSUE TITLE
Vs1.1 mac百度ai无法执行下去

### ISSUE THREAD

**Issue by zijun-he** [lisztomania-Zero/learning-power#41]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    OPTIONS_MANAGE.Init_Options()
  File "/Users/**/Desktop/learning-power-master/inside/Options/Options_Manage.py", line 97, in Init_Options
    cls.__Baidu_AI()
  File "/Users/zrz/Desktop/learning-power-master/inside/Options/Options_Manage.py", line 77, in __Baidu_AI
    with open(PATH().Baidu_AI_On, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept/on'

**Comment by e790a8** [comment]
> Traceback (most recent call last):
> File "main.py", line 23, in
> OPTIONS_MANAGE.Init_Options()
> File "/Users/**/Desktop/learning-power-master/inside/Options/Options_Manage.py", line 97, in Init_Options
> cls.__Baidu_AI()
> File "/Users/zrz/Desktop/learning-power-master/inside/Options/Options_Manage.py", line 77, in __Baidu_AI
> with open(PATH().Baidu_AI_On, 'w', encoding='utf-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '~/Desktop/learning-power-master/inside/Task/Mitmdump/Intercept/on'

文件路径问题，现在已更新为绝对路径模式，我现在搞不清mac的文件路径了。
