### ISSUE TITLE
等着你的更新吧

### ISSUE THREAD

**Issue by zhangop9** [lisztomania-Zero/learning-power#42]
可是读文章，专项答题，别的不能用

**Comment by e790a8** [comment]
> 可是读文章，专项答题，别的不能用

咋啦？

**Comment by zhangop9** [comment]
我是win10 python 3.8 google 88.0.4324.150
用别文件的可以刷起，用你的文件有错误，但是这个能持久，读文章，专项答题两项正常得分，今天都刷满了
明天我再试一下。看有么提示！
能不能做个配置文件，开始的三个问题可以设置好，
再有就要想增加一个定时运行的功能，每天可以间隔一小时，周一7点运行，周二就8点运行
实现一个帐号的盲刷。

**Comment by zhangop9** [comment]
早上试了一下，只有[2]视频不能用

选择任务(空为退出):2
正在分发视频任务
检测到视频任务数不足，自动获取任务集
解析任务集中
解析为文章任务集
正在分发视频任务
检测到视频任务数不足，自动获取任务集
解析任务集中
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    task.Task()
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Manage.py", line 213, in Task
    self.__Check_Video()
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Manage.py", line 124, in __Check_Video
    self.__Video(num=p, tq=(c*4)//p)
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Manage.py", line 75, in __Video
    tasks = TASK_INIT().Assigning_Video(num=num)
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Init.py", line 119, in Assigning_Video
    return self.Assigning_Video(num=num)
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Init.py", line 118, in Assigning_Video
    self.Init_Article_Video()
  File "D:\autoxue\au\learning-power-1.1\inside\Task\Task_Init.py", line 66, in Init_Article_Video
    for temp in html.json():
  File "D:\Python\Python38-32\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Python\Python38-32\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "D:\Python\Python38-32\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "D:\Python\Python38-32\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "D:\Python\Python38-32\lib\site-packages\simplejson\scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "D:\Python\Python38-32\lib\site-packages\simplejson\scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shigubuhua** [comment]
> 我是win10 python 3.8 google 88.0.4324.150
> 用别文件的可以刷起，用你的文件有错误，但是这个能持久，读文章，专项答题两项正常得分，今天都刷满了
> 明天我再试一下。看有么提示！
> 能不能做个配置文件，开始的三个问题可以设置好，
> 再有就要想增加一个定时运行的功能，每天可以间隔一小时，周一7点运行，周二就8点运行
> 实现一个帐号的盲刷。

windows 可以使用系统的计划任务来实现

**Comment by e790a8** [comment]
> Task_Init

这个是偶然性的错误，你再试试

**Comment by simonchen007** [comment]
我也一样，只有[2]视频不能用，运行几次了，还是报同样的错。而且我实用的是相同版本的chrom浏览器。
@lisztomania-Zero  有解决方案不？
