### ISSUE TITLE
新版本运行错误

### ISSUE THREAD

**Issue by againboy** [lisztomania-Zero/learning-power#49]
D:\learning-power-1.0>python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from inside.Options.Options_Manage import OPTIONS_MANAGE
  File "D:\learning-power-1.0\inside\Options\Options_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
  File "D:\learning-power-1.0\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in <module>
    from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
  File "D:\learning-power-1.0\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

D:\learning-power-1.0>

大佬请帮忙看看

**Comment by e790a8** [comment]
> D:\learning-power-1.0>python main.py
> Traceback (most recent call last):
> File "main.py", line 14, in
> from inside.Options.Options_Manage import OPTIONS_MANAGE
> File "D:\learning-power-1.0\inside\Options\Options_Manage.py", line 10, in
> from inside.Baidu_AI.Baidu_AI_Manage import BAIDU_AI_MANAGE
> File "D:\learning-power-1.0\inside\Baidu_AI\Baidu_AI_Manage.py", line 10, in
> from inside.Baidu_AI.Baidu_AI_Tools import BAIDU_AI_TOOLS
> File "D:\learning-power-1.0\inside\Baidu_AI\Baidu_AI_Tools.py", line 11, in
> import cv2
> ModuleNotFoundError: No module named 'cv2'
> 
> D:\learning-power-1.0>
> 
> 大佬请帮忙看看

opencv-python依赖没装
