### ISSUE TITLE
chrome 更新到89版出现如下问题。请问怎么解决

### ISSUE THREAD

**Issue by chieftainzhang** [lisztomania-Zero/learning-power#60]
检测到视频任务数不足，自动获取任务集
解析任务集中
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    task.Task()
  File "/home/zhang/learning-power-master/inside/Task/Task_Manage.py", line 213, in Task
    self.__Check_Video()
  File "/home/zhang/learning-power-master/inside/Task/Task_Manage.py", line 124, in __Check_Video
    self.__Video(num=p, tq=(c*4)//p)
  File "/home/zhang/learning-power-master/inside/Task/Task_Manage.py", line 75, in __Video
    tasks = TASK_INIT().Assigning_Video(num=num)
  File "/home/zhang/learning-power-master/inside/Task/Task_Init.py", line 119, in Assigning_Video
    return self.Assigning_Video(num=num)
  File "/home/zhang/learning-power-master/inside/Task/Task_Init.py", line 118, in Assigning_Video
    self.Init_Article_Video()
  File "/home/zhang/learning-power-master/inside/Task/Task_Init.py", line 66, in Init_Article_Video
    for temp in html.json():
  File "/home/zhang/.local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chieftainzhang** [comment]
重开又好了。奇了怪

**Comment by klcb2010** [comment]
大胸弟能不能整个详细从安装到使用的教程？我从运行main. py就出错了
