### ISSUE TITLE
运行出错，找不到模块，请教下

### ISSUE THREAD

**Issue by w878923** [lisztomania-Zero/learning-power#61]
是否静音(Y/n):y
是否显示自动化过程(y/N):y
是否持久化登录(Y/n):y
是否使用百度AI(y/N):n
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\mitmdump.exe\__main__.py", line 4, in <module>
  File "c:\program files\python\lib\site-packages\mitmproxy\tools\main.py", line 9, in <module>
    from mitmproxy import exceptions, master
  File "c:\program files\python\lib\site-packages\mitmproxy\master.py", line 7, in <module>
    from mitmproxy import addonmanager
  File "c:\program files\python\lib\site-packages\mitmproxy\addonmanager.py", line 8, in <module>
    from mitmproxy import eventsequence
  File "c:\program files\python\lib\site-packages\mitmproxy\eventsequence.py", line 5, in <module>
    from mitmproxy import http
  File "c:\program files\python\lib\site-packages\mitmproxy\http.py", line 6, in <module>
    from mitmproxy.net import http
  File "c:\program files\python\lib\site-packages\mitmproxy\net\http\__init__.py", line 1, in <module>
    from mitmproxy.net.http.request import Request
  File "c:\program files\python\lib\site-packages\mitmproxy\net\http\request.py", line 9, in <module>
    from mitmproxy.net.http import message
  File "c:\program files\python\lib\site-packages\mitmproxy\net\http\message.py", line 6, in <module>
    from mitmproxy.net.http import encoding
  File "c:\program files\python\lib\site-packages\mitmproxy\net\http\encoding.py", line 11, in <module>
    import brotli
  File "c:\program files\python\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: 找不到指定的模块。
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    if LOGIN(task_driver=driver.Task).Login():
  File "F:\inside\Login\Login.py", line 324, in Login
    return self._Login()
  File "F:\inside\Login\Login.py", line 275, in _Login
    self.__driver.get(url=API().Login.geturl())
  File "C:\Program Files\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Program Files\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: chrome=89.0.4389.82)
  (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Windows NT 10.0.15063 x86_64)

**Comment by w878923** [comment]
![新建位图图像](https://user-images.githubusercontent.com/79885418/110216345-a07da280-7ee9-11eb-917d-6714657c786e.jpg)

**Comment by 506430136** [comment]
应该是类库不全，你要在本地安装这些类库
