### ISSUE TITLE
大佬运行报错

### ISSUE THREAD

**Issue by qq290598268** [lisztomania-Zero/learning-power#68]
是否静音(Y/n):
是否显示自动化过程(y/N):
是否持久化登录(Y/n):
是否使用百度AI(y/N):
Traceback (most recent call last):
  File "D:\toosl\learning-power-master\main.py", line 27, in <module>
    network.Init(driver=driver.Task)
  File "D:\toosl\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
    return DRIVER_INIT().Task_Driver
  File "D:\toosl\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
    self.__instances['Task'] = Chrome(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.19042 x86_64)

看不出是什么问题

**Comment by qq290598268** [comment]
是否静音(Y/n):
是否显示自动化过程(y/N):
是否持久化登录(Y/n):
是否使用百度AI(y/N):
检测到驱动不支持本机Chrome
驱动自动下载中
chromedriver_win32.zip: 100%|█████| 5.43M/5.43M [00:08<00:00, 610kB/s]
驱动自动下载完毕
文件大小为5.181962013244629MB
Traceback (most recent call last):
  File "D:\toosl\learning-power-master\main.py", line 27, in <module>
    network.Init(driver=driver.Task)
  File "D:\toosl\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
    return DRIVER_INIT().Task_Driver
  File "D:\toosl\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
    self.__instances['Task'] = Chrome(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 89.0.4389.114 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Windows NT 10.0.19042 x86_64)

PS D:\toosl\learning-power-master>

**Comment by e790a8** [comment]
> 是否静音(Y/n):
> 是否显示自动化过程(y/N):
> 是否持久化登录(Y/n):
> 是否使用百度AI(y/N):
> Traceback (most recent call last):
> File "D:\toosl\learning-power-master\main.py", line 27, in
> network.Init(driver=driver.Task)
> File "D:\toosl\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
> return DRIVER_INIT().Task_Driver
> File "D:\toosl\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
> self.__instances['Task'] = Chrome(
> File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in **init**
> RemoteWebDriver.**init**(
> File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.19042 x86_64)
> 
> 看不出是什么问题

你的Chrome是原装的吗？
这个报错是没找到Chrome的位置
而，本项目使用的是默认路径

**Comment by qq290598268** [comment]
> > 是否静音(Y/n):
> > 是否显示自动化过程(y/N):
> > 是否持久化登录(Y/n):
> > 是否使用百度AI(y/N):
> > Traceback (most recent call last):
> > File "D:\toosl\learning-power-master\main.py", line 27, in
> > network.Init(driver=driver.Task)
> > File "D:\toosl\learning-power-master\inside\Driver\Driver_Manage.py", line 86, in Task
> > return DRIVER_INIT().Task_Driver
> > File "D:\toosl\learning-power-master\inside\Driver\Driver_Init.py", line 93, in Task_Driver
> > self.__instances['Task'] = Chrome(
> > File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in **init**
> > RemoteWebDriver.**init**(
> > File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "C:\Program Files\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
> > (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.19042 x86_64)
> > 看不出是什么问题
> 
> 你的Chrome是原装的吗？
> 这个报错是没找到Chrome的位置
> 而，本项目使用的是默认路径

我用的绿色版本，好这就去切换安装版本
