### ISSUE TITLE
=进程已结束？ 没法搞呀  

### ISSUE THREAD

**Issue by klcb2010** [lisztomania-Zero/learning-power#69]
浏览器也安装了，pip也安装了 。到这里就报错  求教大神

**Comment by klcb2010** [comment]
"D:\My Documents\Desktop\learning\venv\Scripts\python.exe" "D:/My Documents/Desktop/learning/main.py"
Traceback (most recent call last):
  File "D:/My Documents/Desktop/learning/main.py", line 11, in <module>
    from inside.Config.System import SYSTEM
  File "D:\My Documents\Desktop\learning\inside\Config\System.py", line 30
    def Supports(self) -> FrozenSet:
                       ^
SyntaxError: invalid syntax
