### ISSUE TITLE
这错误是怎么回事呢？

### ISSUE THREAD

**Issue by acodealaw** [lisztomania-Zero/learning-power#71]
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    if LOGIN(task_driver=driver.Task).Login():
  File "/home/jay/桌面/learning-power/inside/Login/Login.py", line 324, in Login
    return self._Login()
  File "/home/jay/桌面/learning-power/inside/Login/Login.py", line 278, in _Login
    QR_VESSEL().Show_QR(qr=qr)
  File "/home/jay/桌面/learning-power/inside/Template/Meta_Singleton.py", line 27, in __call__
    cls.__instances[cls] = super(SINGLETON, cls).__call__(*args,
  File "/home/jay/桌面/learning-power/inside/Login/QR_Vessel.py", line 24, in __init__
    self.__driver = DRIVER_MANAGE().QR
  File "/home/jay/桌面/learning-power/inside/Driver/Driver_Manage.py", line 106, in QR
    return DRIVER_INIT().QR_Driver
  File "/home/jay/桌面/learning-power/inside/Driver/Driver_Init.py", line 127, in QR_Driver
    self.__instances['QR'].set_window_size(width=50, height=350)
  File "/home/jay/.virtualenvs/py3_django_1.11.11/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/home/jay/.virtualenvs/py3_django_1.11.11/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1180, in set_window_rect
    return self.execute(Command.SET_WINDOW_RECT, {"x": x, "y": y,
  File "/home/jay/.virtualenvs/py3_django_1.11.11/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jay/.virtualenvs/py3_django_1.11.11/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'
  (Session info: chrome=90.0.4430.72)

**Comment by acodealaw** [comment]
浏览器版本不对
