### ISSUE TITLE
大佬这是什么毛病啊

### ISSUE THREAD

**Issue by ChilliShark** [lisztomania-Zero/learning-power#8]
请选择任务:
1、文章 2、视频 3、每日答题     4、每周答题     5、专项答题（此项有点BUG）
选择(选项请使用空格隔开，退出输入0):4
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    task_manage.start()
  File "C:\Users\54075\Desktop\learning-power-master\task\task_manage.py", line 314, in start
    self.__accomplish_weekly_answer()
  File "C:\Users\54075\Desktop\learning-power-master\task\task_manage.py", line 294, in __accomplish_weekly_answer
    self.__do_weekly_answer_task()
  File "C:\Users\54075\Desktop\learning-power-master\task\task_manage.py", line 242, in __do_weekly_answer_task
    num = self.__weekly_task.get_topic()
  File "C:\Users\54075\Desktop\learning-power-master\tools\analysis.py", line 287, in get_topic
    index: int = get_random.get_random_int(0, topic_num - 1)
  File "C:\Users\54075\Desktop\learning-power-master\tools\get_random.py", line 15, in get_random_int
    return random.randint(a=a, b=b)
  File "C:\Users\54075\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "C:\Users\54075\AppData\Local\Programs\Python\Python38-32\lib\random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, 0, 0)

**Comment by lisztomania-Zero** [comment]
你每周答题是不是答完了

**Comment by ChilliShark** [comment]
> 你每周答题是不是答完了

我看上面写着每周答题5.0
应该是没做完的才对啊

**Comment by lisztomania-Zero** [comment]
那就是 ( topic_num - 1)<0，导致的报错，你重启一下脚本，看行不行

**Comment by ChilliShark** [comment]
> 那就是 ( topic_num - 1)<0，导致的报错，你重启一下脚本，看行不行

试过重启脚本重启电脑啥的，没有效果，现在运行选项5没问题，不过已经运行快半小时了.....

**Comment by lisztomania-Zero** [comment]
5选项尽量不要用，答案识别有点问题

**Comment by lisztomania-Zero** [comment]
4选项还是用不了吗？

**Comment by ChilliShark** [comment]
> 4选项还是用不了吗？

对，用不了

**Comment by lisztomania-Zero** [comment]
你的每周答题，可答的应该是没有了，也就是说你的每周答题应该答光了，导致获取不到新的答题项

**Comment by holodfall** [comment]
用前登录APP看一下，如果每日 每周 专项答题  这些已经满分了，或者没题答了，就不要输入相关序号，不然报错
