### ISSUE TITLE
从2021年10月20日开始好像是不是网站有更新，目前进不去了

### ISSUE THREAD

**Issue by jd04063221** [lisztomania-Zero/learning-power#81]
是否静音(Y/n):
是否显示自动化过程(y/N):
是否持久化登录(Y/n):
是否使用百度AI(y/N):
项目地址:https://github.com/lisztomania-Zero/learning-power
用户ID:594721529
等级:9	段位:九天揽月	全国排名:17224999
总积分:25132.0	今日积分:1.0
每日积分细则:

卡在这里了

**Comment by paranoiagu** [comment]
看：https://github.com/lisztomania-P/learning-power/pull/80
我也改了， 然后发现已经有了mr

**Comment by jd04063221** [comment]
> 看：#80 我也改了， 然后发现已经有了mr

收到，已经先手动修改了

**Comment by woodenhao** [comment]
> > 看：#80 我也改了， 然后发现已经有了mr
> 
> 收到，已经先手动修改了

我就用自带的IDLE编辑把那几个文件几处都改了然后不能运行了 出错，是还需要其他什么步骤吗 不太懂
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from inside.Login.Login import LOGIN
  File "C:\Users\woode\Desktop\pythonlol\learning-power-1.1\inside\Login\Login.py", line 24, in <module>
    from inside.Info.Info_Manage import INFO_MANAGE
  File "C:\Users\woode\Desktop\pythonlol\learning-power-1.1\inside\Info\Info_Manage.py", line 11, in <module>
    from inside.Info.Get_Info import GET_INFO
  File "C:\Users\woode\Desktop\pythonlol\learning-power-1.1\inside\Info\Get_Info.py", line 134
    else:
    ^
SyntaxError: invalid syntax
